name: Learning Flutter for Native iOS Developers

# Accepts 'flutter' or 'dart'
type: flutter

# Configuration for each step 
steps:
  - name: Flutter vs UIKit vs SwiftUI
    directory: flutter_vs_uikit_vs_swiftui
    has_solution: true
  - name: Rendering in Flutter vs Native iOS
    directory: rendering_in_flutter_vs_native_ios
    has_solution: true
  - name: StatelessWidget
    directory: statelesswidget
    has_solution: true
  - name: StatefulWidget
    directory: statefulwidget
    has_solution: true
  - name: Rendering Text
    directory: rendering_text
    has_solution: true